name: Build APK with Buildozer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Run Buildozer in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          kivy/buildozer:stable \
          buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app
        path: bin/*.apk
