name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk python3-setuptools git wget

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install --user buildozer cython virtualenv

      - name: Set up Android SDK and NDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" || true

      - name: Initialize Buildozer
        run: |
          buildozer init || true
          buildozer android clean || true

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk

