name: Build APK with Buildozer

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          libffi-dev libssl-dev python3-dev python3-pip build-essential \
          git zip unzip openjdk-17-jdk libncurses5-dev
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Accept SDK licenses
      run: |
        mkdir -p ~/.android
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/repositories.cfg || true

    - name: Set up Buildozer environment
      run: |
        buildozer init || true  # si ya existe no falla
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/# android.sdk_path =/android.sdk_path = \/home\/runner\/.buildozer\/android\/platform\/android-sdk/' buildozer.spec
        sed -i 's/# android.ndk_path =/android.ndk_path = \/home\/runner\/.buildozer\/android\/platform\/android-ndk-r25b/' buildozer.spec
        sed -i 's/# android.build_tools_version =/android.build_tools_version = 30.0.3/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk
