on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias del sistema
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential git zip unzip openjdk-17-jdk \
          python3-pip python3-setuptools python3-venv \
          libffi-dev libssl-dev \
          libsqlite3-dev zlib1g-dev \
          libbz2-dev libreadline-dev liblzma-dev \
          libncurses5-dev libgdbm-dev libnss3-dev libxml2-dev libxslt1-dev \
          curl

    - name: Instalar Buildozer
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install buildozer cython

    - name: Compilar APK
      run: |
        source venv/bin/activate
        buildozer android debug

    - name: Guardar artefacto APK
      uses: actions/uplo
