name: Build APK with Buildozer

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          libffi-dev libssl-dev python3-dev python3-pip build-essential \
          git zip unzip openjdk-17-jdk libncurses5-dev
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Update Buildozer & SDK components
      run: |
        buildozer android update

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk
