name: Build APK with Buildozer

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Accept Android SDK licenses and install build-tools
        run: |
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true
          yes | sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" || true

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: bin/*.apk

